const level1 = new Level(
    [
        new PufferFish(),
        new PufferFish(),
        new PufferFish(),
        new JellyFish(),
        new JellyFish(),
        new JellyFish(),
        new Endboss(),
    ],
    [
        new BackgroundObjects('img/3. Background/Layers/5. Water/L2.png', -719),
        new BackgroundObjects('img/3. Background/Layers/1. Light/2.png', -719),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L2.png', -719),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L2.png', -719),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L2.png', -719),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L1.png', 0),
        new BackgroundObjects('img/3. Background/Layers/1. Light/1.png', 0),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L1.png', 0),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L1.png', 0),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L1.png', 0),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L2.png', 719),
        new BackgroundObjects('img/3. Background/Layers/1. Light/2.png', 719),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L2.png', 719),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L2.png', 719),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L2.png', 719),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L1.png', 719*2),
        new BackgroundObjects('img/3. Background/Layers/1. Light/1.png', 719*2),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L1.png', 719*2),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L1.png', 719*2),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L1.png', 719*2),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L2.png', 719*3),
        new BackgroundObjects('img/3. Background/Layers/1. Light/2.png', 719*3),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L2.png', 719*3),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L2.png', 719*3),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L2.png', 719*3),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L1.png', 719*4),
        new BackgroundObjects('img/3. Background/Layers/1. Light/1.png', 719*4),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L1.png', 719*4),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L1.png', 719*4),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L1.png', 719*4),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L2.png', 719*5),
        new BackgroundObjects('img/3. Background/Layers/1. Light/2.png', 719*5),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L2.png', 719*5),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L2.png', 719*5),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L2.png', 719*5),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L1.png', 719*6),
        new BackgroundObjects('img/3. Background/Layers/1. Light/1.png', 719*6),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L1.png', 719*6),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L1.png', 719*6),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L1.png', 719*6),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L2.png', 719*7),
        new BackgroundObjects('img/3. Background/Layers/1. Light/2.png', 719*7),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L2.png', 719*7),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L2.png', 719*7),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L2.png', 719*7),
    ],
);