/**
 * In this data set, the first level is created 
 * 
 */
let level1 = new Level(
    [
        new PufferFish(this.world),
        new PufferFish(this.world),
        new PufferFish(this.world),
        new JellyFish(this.world),
        new JellyFish(this.world),
        new JellyFish(this.world),
        new Endboss(),
    ],
    [
        new BackgroundObjects('img/3. Background/Layers/5. Water/L2.png', -719),
        new BackgroundObjects('img/3. Background/Layers/1. Light/2.png', -719),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L2.png', -719),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L2.png', -719),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L2.png', -719),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L1.png', 0),
        new BackgroundObjects('img/3. Background/Layers/1. Light/1.png', 0),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L1.png', 0),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L1.png', 0),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L1.png', 0),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L2.png', 720),
        new BackgroundObjects('img/3. Background/Layers/1. Light/2.png', 720),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L2.png', 720),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L2.png', 720),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L2.png', 720),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L1.png', 720 * 2),
        new BackgroundObjects('img/3. Background/Layers/1. Light/1.png', 720 * 2),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L1.png', 720 * 2),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L1.png', 720 * 2),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L1.png', 720 * 2),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L2.png', 720 * 3),
        new BackgroundObjects('img/3. Background/Layers/1. Light/2.png', 720 * 3),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L2.png', 720 * 3),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L2.png', 720 * 3),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L2.png', 720 * 3),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L1.png', 720 * 4),
        new BackgroundObjects('img/3. Background/Layers/1. Light/1.png', 720 * 4),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L1.png', 720 * 4),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L1.png', 720 * 4),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L1.png', 720 * 4),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L2.png', 720 * 5),
        new BackgroundObjects('img/3. Background/Layers/1. Light/2.png', 720 * 5),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L2.png', 720 * 5),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L2.png', 720 * 5),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L2.png', 720 * 5),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L1.png', 720 * 6),
        new BackgroundObjects('img/3. Background/Layers/1. Light/1.png', 720 * 6),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L1.png', 720 * 6),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L1.png', 720 * 6),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L1.png', 720 * 6),
        new BackgroundObjects('img/3. Background/Layers/5. Water/L2.png', 720 * 7),
        new BackgroundObjects('img/3. Background/Layers/1. Light/2.png', 720 * 7),
        new BackgroundObjects('img/3. Background/Layers/4.Fondo 2/L2.png', 720 * 7),
        new BackgroundObjects('img/3. Background/Layers/3.Fondo 1/L2.png', 720 * 7),
        new BackgroundObjects('img/3. Background/Layers/2. Floor/L2.png', 720 * 7),
    ],
    [
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
    ],
    [
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
        new Poison(),
    ],
);